version: '2'

services:
  node:
    build: ./
    ports: 
    - "3000:3000"
    - "27017:27017"
    volumes:
    - .\:/usr/src/app
    links:
    - mongo
  
  mongo:
    image: mongo
    ports: 
    - "27017:27017"

